### ISSUE TITLE
Plugin failed to load because module could not be found & Could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by moseechev** [mordentral/VRExpansionPlugin#15]
ok so i tried pretty much everything
LITTERALLY EVERYTHING I SHOULD SAY
i've created 3 branches on different websites and noone was able to help me
your plugin requires a c++ project and not a blueprint project, BUT THIS IS IMPOSSIBLE. you can't create a vr project with c++ code. i tried adding the "blank dummy c++ file into the project", i failed. the engine said i have to rebuild the project, and when i'm trying to do it, it says Could not be compiled. Try rebuilding from source manually.
i actually have no idea what to do and begging for help

**Comment by moseechev** [comment]
https://imgur.com/a/pfv1A8a
https://imgur.com/a/sqEkZbL
Plugin failed to load because module could not be found happens if the plugin is installed into the engine's Plugins folder.
Could not be compiled. Try rebuilding from source manually. happens if the plugin's installed into the project's Plugins folder. i don't have build.cs nor any .sln files, again, this is not a c++ project
i also gotta say that i'm not sure if the engine itself can recognize the visual studio, maybe it recognizes it partially or something, but i had the error in the engine itself that was saying i should install visual studio 2019, i reinstalled the visual studio and the issue dissapeared, but another appeared..

**Comment by moseechev** [comment]
i'm also unable to create ANY project template in c++ code
https://ibb.co/jkDJPZD (imgur servers were down, i've found another photohosting)

**Comment by mordentral** [comment]
If you add a c++ file in editor (big green button) it will auto generate the files for you and convert it to a c++ project.

Also there is a pre-made example template.

There precompiled binaries should also work without being a c++ project if you download them and put them in the plugins folder, I just suggest that people generally not use them if they can avoid it since an actual repo copy is always more up to date and can be updated / recompiled on the fly when new engine versions come out.

**Comment by timothyTheCoder** [comment]
Has the issue been resolved yet?
1) Did you follow the installation setup described here? 
Make sure you install all required Visual Studio plugins for Unreal Engine described here: https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/VisualStudioSetup/

2) Then check out this example project that comes with all the plugins installed, a handy test level, a working pawn and navigation. Check out readme.md but basically: check out code, right click a file and select ‘generate VS files’ then open the project and if a re-compile window apears just click to recompile. Then project will open with the test level and everything good to go for you to press Play VR Preview and have a working pawn, hands and movement. 
https://github.com/mordentral/VRExpPluginExample

3) if 2) works then try and use the plugins into your own BluePrint project by following these steps https://vreue4.com/documentation?section=installation

If you have questions somewhere with these steps, ask away and will try and help you as the plug-ins are amazing.

**Comment by Florin0211** [comment]
Hi, does this plugin also work on U5.1.1?
