### ISSUE TITLE
Error packaging for Windows

### ISSUE THREAD

**Issue by Zananok** [mordentral/VRExpansionPlugin#18]
Using: Win11 Pro vm, UE 4.27 and Windows 10.0.19041.0 SDK
Using latest VRExpansionPlugin from the master branch (b5bdab97c34e1f0b23c215d4012b45c66811ef81)

There are no compiler issues when building for running on the UE4 editor, however, once I attempt to package for shipping, I can't get past:

UBT-ProjectName-Win64-Shipping.txt
> ParallelExecutor.ExecuteActions:   [25/31] GS_GunTools.cpp
> ParallelExecutor.ExecuteActions:   [26/31] Module.VRExpansionPlugin.3_of_4.cpp
> ParallelExecutor.ExecuteActions:   [27/31] Module.VRExpansionPlugin.2_of_4.cpp
> ParallelExecutor.ExecuteActions:   [28/31] Module.VRExpansionPlugin.4_of_4.cpp
> UnrealBuildTool.Main: CompilationResultException: Error: OtherCompilationError
> UnrealBuildTool.Main:    at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute) in D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 230
> UnrealBuildTool.Main:    at UnrealBuildTool.BuildMode.Build(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile) in D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 485
> UnrealBuildTool.Main:    at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 226
> UnrealBuildTool.Main:    at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 557
> Timeline.Print: Timeline:
> Timeline.Print: 
> Timeline.Print: [ 0.000]
> Timeline.Print: [ 0.000](+0.022) <unknown>
> Timeline.Print: [ 0.022](+0.003) FileMetadataPrefetch.QueueEngineDirectory()
> Timeline.Print: [ 0.026](+0.202) XmlConfig.ReadConfigFiles()
> Timeline.Print: [ 0.229](+0.000) SingleInstanceMutex.Acquire()
> Timeline.Print: [ 0.229](+0.093) UEBuildPlatform.RegisterPlatforms()
> Timeline.Print:   0.230          [ 0.001](+0.069) Initializing InstalledPlatformInfo
> Timeline.Print:   0.299          [ 0.070](+0.000) Querying types
> Timeline.Print:   0.301          [ 0.071](+0.001) MacPlatformFactory
> Timeline.Print:   0.302          [ 0.072](+0.000) TVOSPlatformFactory
> Timeline.Print:   0.302          [ 0.073](+0.015) AndroidPlatformFactory
> Timeline.Print:   0.317          [ 0.088](+0.000) HoloLensPlatformFactory
> Timeline.Print:   0.318          [ 0.088](+0.000) IOSPlatformFactory
> Timeline.Print:   0.318          [ 0.088](+0.003) LinuxPlatformFactory
> Timeline.Print:   0.321          [ 0.092](+0.000) LuminPlatformFactory
> Timeline.Print:   0.321          [ 0.092](+0.001) WindowsPlatformFactory
> Timeline.Print: [ 0.328](+0.010) TargetDescriptor.ParseCommandLine()
> Timeline.Print: [ 0.338](+0.030) <unknown>
> Timeline.Print: [ 0.369](+0.870) UEBuildTarget.Create()
> Timeline.Print:   0.372          [ 0.003](+0.345) RulesCompiler.CreateTargetRulesAssembly()
> Timeline.Print:   0.372            0.003          [ 0.000](+0.166) <unknown>
> Timeline.Print:   0.539            0.170          [ 0.166](+0.033) Finding engine modules
> Timeline.Print:   0.572            0.203          [ 0.200](+0.006) Finding plugin modules
> Timeline.Print:   0.578            0.209          [ 0.206](+0.111) <unknown>
> Timeline.Print:   0.690            0.321          [ 0.317](+0.007) Finding program modules
> Timeline.Print:   0.697            0.328          [ 0.325](+0.002) Finding program targets
> Timeline.Print:   0.718          [ 0.349](+0.084) RulesAssembly.CreateTargetRules()
> Timeline.Print:   0.822          [ 0.452](+0.046) UEBuildTarget constructor
> Timeline.Print:   0.825            0.456          [ 0.003](+0.041) Reading source file metadata cache
> Timeline.Print:   0.868          [ 0.499](+0.370) UEBuildTarget.PreBuildSetup()
> Timeline.Print: [ 1.242](+7.690) UEBuildTarget.Build()
> Timeline.Print:   1.242          [ 0.000](+0.035) <unknown>
> Timeline.Print:   1.277          [ 0.035](+0.042) ExternalExecution.SetupUObjectModules()
> Timeline.Print:   1.319          [ 0.077](+0.053) <unknown>
> Timeline.Print:   1.373          [ 0.131](+6.797) Executing UnrealHeaderTool
> Timeline.Print:   8.174          [ 6.931](+0.001) ExternalExecution.ResetCachedHeaderInfo()
> Timeline.Print:   8.175          [ 6.933](+0.050) ExternalExecution.UpdateDirectoryTimestamps()
> Timeline.Print:   8.233          [ 6.991](+0.628) UEBuildBinary.Build()
> Timeline.Print:   8.862          [ 7.620](+0.070) <unknown>
> Timeline.Print: [ 8.940](+0.002) ActionGraph.CheckPathLengths
> Timeline.Print: [ 8.952](+0.000) Reading action history
> Timeline.Print: [ 8.952](+0.014) Reading dependency cache
> Timeline.Print: [ 8.967](+0.069) Prefetching include dependencies
> Timeline.Print: [ 9.037](+1.484) Cache outdated actions
> Timeline.Print: [10.536](+23.986) ActionGraph.ExecuteActions()
> Timeline.Print: [34.523](+0.028) <unknown>
> Timeline.Print: [34.551](+0.000) FileMetadataPrefetch.Stop()

Any guesses on why I have this issue? I attempted deleting all "Intermediate" folders involved (main project's Intermediate, VRExpansionPlugin's Intermediate, and OpenVRExpansionPlugin's Intermediate), but had no success.

In the past, I have managed to build when using UE 4.26, but as I couldn't compile now in UE 4.27, I updated the Win SDK to the latest version, just in case, however, no success.

In addition, I also have ran a "Verify" on UE 4.27 installation to make sure there are no engine corrupted files

Best regards

**Comment by mordentral** [comment]
I've never seen that compilation error, its not bad source, something wrong with the toolchain itself.

**Comment by VitorOI** [comment]
Have you been able to fix this? Currently with UE5 and can't package either. The template project works though

**Comment by mordentral** [comment]
> Have you been able to fix this? Currently with UE5 and can't package either. The template project works though

Do you actually have the same issue? its very unlikely, you can message me with the debug log, but normally packaging issues don't directly have to do with the plugin.

**Comment by VitorOI** [comment]
> > Have you been able to fix this? Currently with UE5 and can't package either. The template project works though
> 
> Do you actually have the same issue? its very unlikely, you can message me with the debug log, but normally packaging issues don't directly have to do with the plugin.

I discovered I had a compilation issue with another file of the project which is not related to the plugin. Weird that it doesn't cause issues when I build the project, only when I tried to package it. At any case, I'm trying to fix that issue
