### ISSUE TITLE
How to disable capsule rotation?

### ISSUE THREAD

**Issue by TrueCreators** [mordentral/VRExpansionPlugin#19]
How to disable capsule rotation with camera?
This is necessary to work with ALSv4

**Comment by mordentral** [comment]
The capsule doesn't rotate with the camera, its only visual as im moving its physics scene representation.

I also doubt ALSv4 will just slot in and work perfectly without modifications, I know one user adjusted where ALSv4 calculates its velocity to have it working with a VRE std character.

**Comment by mordentral** [comment]
In the end regardless, I don't entirely understand the need for ALSv4 anyway since its not providing much in the way of useful features for VR, the only time I would see it being that useful is third person and you don't need the offsettable capsule for that anyway.
