### ISSUE TITLE
Building .sln fails

### ISSUE THREAD

**Issue by fuckyouepic** [mordentral/VRExpansionPlugin#20]
UE5 - EA2
Building the .sln gives me the error "Couldn't find parent type for 'BucketUpdateSubsystem' named 'UTickableWorldSubsystem'"

On googling the error I already found a similar Issue here, but the answer didn't help me to fix it^^

**Comment by mordentral** [comment]
EA2 is defunct, Preview2 is out.

I removed the EA branch as its not the one going forward into UE5 and the EA version of the engine didn't have that new subsystem type.

**Comment by fuckyouepic** [comment]
Oh I see, I didn't realize EA and Preview are different things. Thanks a lot for your hard work!
