### ISSUE TITLE
4.27 locked doesn't build 

### ISSUE THREAD

**Issue by KetchupMoose** [mordentral/VRExpansionPlugin#28]
The latest commits on 4.27 locked were not building for us on oculus branch of 4.27.

We got an error that  TObjectPtr was referenced in vrbpdatatypes.h and that seems to be an unreal 5 identifier?

**Comment by mordentral** [comment]
You didn't pull 4.27-Locked, you somehow pulled Master by mistake.

I just double checked and there are no instances of the TObjectPtr in the 4.27 branch

**Comment by KetchupMoose** [comment]
Thank you, we had another team member pulling it so maybe they did make that mistake.  
They thought they pulled 4.27 but maybe made a mistake.
