### ISSUE TITLE
OculusOpenXR plugin missing in 4.27-locked

### ISSUE THREAD

**Issue by TetraStudiosLegacyAcc** [mordentral/VRExpansionPlugin#31]
Is there any way I can install this plugin, or do I just disable it?
I'm using an Oculus source build of the engine too.

Thanks so much and keep up the great work!

**Comment by mordentral** [comment]
Disable it, they built it's features into an engine module in their branch

**Comment by IIAMATOMIIC** [comment]
Error: VR_MVR could not be compiled. Try rebuilding from source manually.
I'm trying to open my project after adding the plugin, but this error is showing. Please help.

**Comment by mordentral** [comment]
> 

not sure what VR_MVR is, its not this, but generally if you add a source plugin and not precompiled binaries for it you need to open up your code editor (visual studio) and compile the project.

**Comment by IIAMATOMIIC** [comment]
Thank u for reply. I don't know the problem is fixed or not but the project
is opening now without any error😂. Thank u for give us amazing plugin🤟
