### ISSUE TITLE
hands (sometimes one, sometimes both) suddenly stop moving (UE5.1)

### ISSUE THREAD

**Issue by SlySeanDaBomb** [mordentral/VRExpansionPlugin#32]
for some reason my hands will suddenly stop moving sometimes but buttons still work and they move in the oculus menu, it's just in the game.

**Comment by mordentral** [comment]
Are you on a very old 5.1 build? I had a bug very early on in 5.1 that I had to fix regarding that. But I have many many users on the same hardware with no issues since then, and that was them never moving at all.

Tracking itself is handled engine side, the plugin just reads it.

**Comment by SlySeanDaBomb** [comment]
I'm on the release (5.1.1) version of the github source build. is there an issue with that one?

**Comment by mordentral** [comment]
Nope, most are on that, and I am as well. I do most of my testing on airlink quest2 actually. The version with issues would have been within the first week of 5.1's preview I believe.

**Comment by SlySeanDaBomb** [comment]
I use a little bit of airlink, a little bit of cabled link. guess i'm screwed.

**Comment by mordentral** [comment]
Oh you aren't screwed, just need to figure out what is going on with you.

One simple and quick test would be to drop some engine standard controllers into your pawn with a static mesh attached to them and run until the hands freeze. If the engines MotionController component doesn't freeze but mine does, then something is wrong with the plugin itself.

Though I will note that the plugin Freezes the hands if tracking is lost as otherwise they fly away, the default controllers just keep drifting out into the void.

**Comment by SlySeanDaBomb** [comment]
Ok weird thing, it's not happening anymore. It was happening nearly every time i'd play my game to test something if i spent too much time in it, but i've just spent the last 2 or 3 hours trying to reproduce the bug and it's not happening anymore 😅

**Comment by SlySeanDaBomb** [comment]
It started happening again, twice. Both times it happened while I was lagging a lot if that helps.

**Comment by mordentral** [comment]
Really doubt it has anything to do with the plugin itself, like I mentioned the tracking is handled engine side. I impose limits on the tracking but I don't interfere with it.

**Comment by ccxxww123** [comment]
> 

When I put this plugin case into UE5.1, I can't use teleportation, how can I fix this

**Comment by mordentral** [comment]
> > 
> 
> When I put this plugin case into UE5.1, I can't use teleportation, how can I fix this

? It doesn't touch navigation or tracing so that is doubtful. Do you mean when you migrate the example content?

**Comment by ccxxww123** [comment]
> 
When I download the ExpPluginExample to my pc, I choose the teleport nothing happens.I just can use HMDOrient mode .My UE version is 5.1,I checked the expamle vesion is right.

**Comment by mordentral** [comment]
You pressed on the thumbstick?

**Comment by ccxxww123** [comment]
> 
yes，but nothing happens

**Comment by mordentral** [comment]
Sounds like the enhanced inputs aren't being bound too? That or you are using a headset that I don't have default buttons mapped for somehow. Check the enhanced input bindings.

**Comment by ccxxww123** [comment]
> Sounds like the enhanced inputs aren't being bound too? That or you are using a headset that I don't have default buttons mapped for somehow. Check the enhanced input bindings.

I checked the enhanced inputs,i think is no problem.When I chose the other modes（such as Armswing ,it can be work）,its can be work

**Comment by SlySeanDaBomb** [comment]
still having this issue. any fix yet?

**Comment by mordentral** [comment]
> still having this issue. any fix yet?

Is this with oculus? If it is and the controllers are resting for a moment then its hand tracking kicking in. AFAIK you have to disable hand tracking to get around it. They are super over zealous about it taking precedence over controllers.

**Comment by SlySeanDaBomb** [comment]
yeah it's on oculus but I'm afraid that didn't help either. I've been at this for days trying everything to fix it after trying to ignore it for the last few months while just working on my project.

**Comment by mordentral** [comment]
> yeah it's on oculus but I'm afraid that didn't help either. I've been at this for days trying everything to fix it after trying to ignore it for the last few months while just working on my project.

As in disabling the OpenXRHandTracking plugin in the engine?

I don't mean turning it off on my example pawn. Also add some default engine controllers and attach a static mesh to them and see if they do the same. The only controller pausing I have ever seen is from hand tracking kicking in from oculus.

**Comment by SlySeanDaBomb** [comment]
yeah I saw you mention disabling the plugin on discord I think. Also the engine controller stopped too so looks like this is an engine bug.

**Comment by SlySeanDaBomb** [comment]
the issue seems to be fixed in 5.3 (and maybe 5.2, I don't know). glad that's out of the way!

**Comment by mordentral** [comment]
They did make hand tracking less annoying in 5.3 (though not entirely)
