### ISSUE TITLE
Gesture spline material does not change as expected

### ISSUE THREAD

**Issue by DrGuantanamo** [mordentral/VRExpansionPlugin#33]
I use the latest version of the plugin from main branch ([91b3953](https://github.com/mordentral/VRExpansionPlugin/commit/91b39532672f239d1d38b779ca42603297b9dace)) together with UE Version: 5.1.1-23901901+++UE5+Release-5.1

When I draw a gesture with Blueprint.BeginRecord(Target = VRGestureComponent, Run Detection = FALSE, Flatten Gesture = FALSE, Draw Gesture = TRUE, Draw Spline =  TRUE, Sampling HTZ = 30, Sample Buffer Size = 120, Clamping Tolerance = 0.01) with a predefined mesh and a predefined material, everything is fine (see image below on the left hand side). But when I change the material during runtime, e.g. to a green material, it does not behave as expected. 

Steps to reproduce: start game, draw a spline with fire material, stop drawing the spline (spline disappears as expected), change the material to green, start drawing a new spline.

Expectation: When I start drawing a new gesture / spline, it should use the set Spline Material right from the beginning of the new gesture.

What actually happens: After changing material to green during runtime and then beginning a new gesture, it still starts with the old material and after a while, it changes to the green material. See right side of the image. If I change to a third material, I even get the splines drawn in three materials in an infinite loop (first, second, third material). Even when I start with a new gesture, the old materials are still somehow "remembered".

![Gesture_Spline_Bug](https://user-images.githubusercontent.com/60034624/224482185-b6298424-5386-4cc7-8c4a-92645c36efd3.png)

**Comment by mordentral** [comment]
Yeah the gesture spline re-uses the mesh components up until a max number of them in order to avoid spawning more components live (expensive). I hadn't considered changing the material on them live, but it should be easy enough to apply the current material when re-using them.

I can add that fairly easily today for you.

**Comment by mordentral** [comment]
I commited the fix for it to 4.27 and 5.1 branches

**Comment by DrGuantanamo** [comment]
Now, everything is perfect! Many thanks for this fast patch!
