### ISSUE TITLE
GetOpenVRHMDType & GetOpenVRControllerType Crash on the Oculus Quest

### ISSUE THREAD

**Issue by Jackson-Luff** [mordentral/VRExpansionPlugin#4]
Hi there, mordentral.

Love the work you've done on this plugin. 
Both `GetOpenVRHMDType` and `GetOpenVRControllerType` appear to crash the application on the Oculus Quest.
The build settings: arm64, Vulkan, shipped

I've reproduced this in a cutdown project and attached it to this post.
[UDN_VRExpansionBug.zip](https://github.com/mordentral/VRExpansionPlugin/files/5072887/UDN_VRExpansionBug.zip)

If you could address this I would really appreciate. 

Thanks,
Jackson.

**Comment by Jackson-Luff** [comment]
Nevermind - just had to enable Android as whitelisted.

**Comment by mordentral** [comment]
There isn't really a reason for it to have a whitelist, a little unsure when that snuck in there.

When not in a steam compatible OS it should be using compile time flags to not run the steamvr code anyway, i removed the whitelist for now.

**Comment by Jackson-Luff** [comment]
Hi Josh,

No worries at all but I appreciate that it was addressed!

Thanks for the fast response, I appreciate it.
~ Jackson

On 15 Aug 2020, at 12:57 am, Joshua (MordenTral) Statzer <notifications@github.com> wrote:

﻿

There isn't really a reason for it to have a whitelist, a little unsure when that snuck in there.

When not in a steam compatible OS it should be using compile time flags to not run the steamvr code anyway, i removed the whitelist for now.
