### ISSUE TITLE
Object collision seems to break after dropping item using physics hand

### ISSUE THREAD

**Issue by loicmacken** [mordentral/VRExpansionPlugin#40]
![vrplugin_drop_item](https://github.com/mordentral/VRExpansionPlugin/assets/62008600/438f4d14-3a8b-4411-b12c-b56a9f496567)

When picking up an item with the physics hand and then dropping it, it spins around quickly for a while and then ends up in a position that does not fit the object collision. Compare the cube circled green with the one in red in the image, green is before picking it up and red is after.

So picking up the object seems to do something to the object collision or physics and this only happens when using the physical hand. With the command "show collision" activated, the collision of the object is shown unchanged compared to before it was picked up.

Headset: Meta Quest 2 (airlink / cable)
Unreal version: 5.2
Plugin version: Latest example (VRExpPluginExample-master)

**Comment by mordentral** [comment]
Its a known issue with 5.0/chaos and welding skeletal components. I am working on a workaround now that most of the other bugs are fixed with chaos. I had it mostly working when 5.3 came out and I had to set it aside for the moment.

If you turn off the welded body driver on grip it won't do that for now ( though the hand itself will have inaccurate collisions during grip then).

I would expect to have it fixed in 5.2+ fairly soon, I don't think I will back port it to 5.1 or 5.0.

**Comment by loicmacken** [comment]
Thank you for the quick response.

I will keep it for now and wait for the fix.

**Comment by loicmacken** [comment]
Fixed in 5.3
Thank you!

**Comment by mordentral** [comment]
Well if you mean the 5.3 example template, I just turned off the hand collision on attachment for now.

Did it just fix itself in your project without those changes or were you checking the 5.3 example? Because I don't consider that a real fix, just a nasty workaround for now.

**Comment by loicmacken** [comment]
I was using the 5.3 example :)

**Comment by mordentral** [comment]
Ok, well that means its just because of the workaround for now. Which is really not what I want since keeping the hand collision on grip is to be expected with physical hands. But until epic gets around to the skeletal mesh fixes I think its going to have to stay this way for now.

**Comment by loicmacken** [comment]
Ah that is unfortunate to hear.
Hope Epic fixes it soon then :)
