### ISSUE TITLE
Suggestion for Common UI viewport class, Live Coding crashes

### ISSUE THREAD

**Issue by lucasfisher0** [mordentral/VRExpansionPlugin#41]
Hello! With the recent versions of Unreal the Common UI plugin has seen more development and is now used more. Common UI utilizes a custom Game Viewport Client class for some input handling, and the implementation code requires a subclass of the 'CommonGameViewportClient.' This is set under Project Settings > Engine > General Settings > Game Viewport Client Class.

Additionally, I have been crashing over and over in intervals ranging from 5m-30m which according to the logs is always Live Coding interacting with the OpenXR plugin. I don't use this functionality so I have disabled it, but I would like to know if this is an issue for anyone else. I will enable it again to try and grab anything helpful.

Thank you for the plugin.

**Comment by mordentral** [comment]
Not entirely sure what you want here?  Should be able to assign that just fine as is. The live coding crash is a known issue in engine and epic is aware of it.
