### ISSUE TITLE
Player Attachment failed

### ISSUE THREAD

**Issue by KarthikaGopala** [mordentral/VRExpansionPlugin#47]
AttachTo: '/Game/VRE/ExampleMap/UEDPIE_0_MotionControllerMap.MotionControllerMap:PersistentLevel.BP_VRCharacter_C_1.AttachmentProxyRight' already attached to '/Game/VRE/ExampleMap/UEDPIE_0_MotionControllerMap.MotionControllerMap:PersistentLevel.GraspingHandManny_C_2.SkeletalMeshComponent0', would form cycle. Aborting.

**Comment by mordentral** [comment]
did you upgrade a project to 5.2/5.3? i had to alter how the proxy components worked because of some engine issue and the example got modified
